[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit=1.27.0",
    "pandas=2.0.3",
    "requests=2.31.0",
    "python-dotenv=1.1.0",
]
